package com.example.gradle.gradledemo;

import com.example.gradle.gradledemo.accessingdatamysql.User;
//import com.example.gradle.gradledemo.accessingdatamysql.UserRepository;
import org.apache.shiro.SecurityUtils;
import org.apache.shiro.authc.*;
import org.apache.shiro.authz.annotation.RequiresRoles;
import org.apache.shiro.subject.Subject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;

@RestController // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /demo (after Application path)
public class UserController {
//    @Autowired // This means to get the bean called userRepository
//    // Which is auto-generated by Spring, we will use it to handle the data
//    private UserRepository userRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody Map<String, Object> addNewUser (@RequestBody @Valid User user, BindingResult error) throws SQLException {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        if(error.hasErrors()) {
            return success("", error.getAllErrors().get(0).getDefaultMessage());
        }

        System.out.println(error.getAllErrors());
        System.out.println(user.getName());

        return success(user.save(false), "ok");
    }

    @RequiresRoles("admin")
    @GetMapping(path="/all")
    public @ResponseBody Map<String, Object> getAllUsers() throws SQLException {
        Subject currentUser = SecurityUtils.getSubject();

        try {
            UsernamePasswordToken token = new UsernamePasswordToken("lonestarr", "vespa");
            currentUser.login(token);
            //if no exception, that's it, we're done!
        } catch ( UnknownAccountException uae ) {
            //username wasn't in the system, show them an error message?
        } catch ( IncorrectCredentialsException ice ) {
            //password didn't match, try again?
        } catch ( LockedAccountException lae ) {
            //account for that username is locked - can't login.  Show them a message?
        // ... more types exceptions to check if you want ...
        } catch ( AuthenticationException ae ) {
            //unexpected condition - error?
        }

        // This returns a JSON or XML with the users
        return success(User.queryAll(), "ok");
    }

    @PostMapping(path="/login") // Map ONLY POST Requests
    public @ResponseBody Map<String, Object> userLogin (@RequestBody @Valid User user, BindingResult error) throws SQLException {
        Subject currentUser = SecurityUtils.getSubject();

        if ( !currentUser.isAuthenticated() ) {
            //collect user principals and credentials in a gui specific manner
            //such as username/password html form, X509 certificate, OpenID, etc.
            //We'll use the username/password example here since it is the most common.
            //(do you know what movie this is from? ;)
            UsernamePasswordToken token = new UsernamePasswordToken("lonestarr", "vespa");
            //this is all you have to do to support 'remember me' (no config - built in!):
            token.setRememberMe(true);
            currentUser.login(token);
        }

        return success(user.save(false), "ok");
    }

    private Map<String, Object> success(Object data, String message) {
        Map<String, Object> map = new HashMap<>(3);

        map.put("code", 200);
        map.put("data", data);
        map.put("message", message);

        return map;
    }
}