package com.example.gradle.gradledemo;

import com.example.gradle.gradledemo.accessingdatamysql.User;
//import com.example.gradle.gradledemo.accessingdatamysql.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;

@RestController // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /demo (after Application path)
public class UserController {
//    @Autowired // This means to get the bean called userRepository
//    // Which is auto-generated by Spring, we will use it to handle the data
//    private UserRepository userRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody Map<String, Object> addNewUser (@RequestBody @Valid User user, BindingResult error) throws SQLException {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        if(error.hasErrors()) {
            return success("", error.getAllErrors().get(0).getDefaultMessage());
        }

        System.out.println(error.getAllErrors());
        System.out.println(user.getName());

        return success(user.save(false), "ok");
    }

    @GetMapping(path="/all")
    public @ResponseBody Map<String, Object> getAllUsers() throws SQLException {
        // This returns a JSON or XML with the users
        return success(User.queryAll(), "ok");
    }

    private Map<String, Object> success(Object data, String message) {
        Map<String, Object> map = new HashMap<>(3);

        map.put("code", 200);
        map.put("data", data);
        map.put("message", message);

        return map;
    }
}